install.packages("renv")
renv::init()
renv::snapshot()
usethis::use_package(package = "renv", type = "Suggests")
install.packages("rmarkdown")
usethis::use_readme_rmd()
file.create("R/calculate_terminal_velocity.R")
devtools::document()
getwd()
devtools::build()
devtools::check()
devtools::install()
library(velocimeter)
calculate.terminal.velocity.phys(file = "terminal_velocity_analysis20219191543/agri-short_00000.aviResults.txt",
                                 min.size = 10,min.circularity = 0.05,fps = 130,tubelength = 1.075)
